version: '3.9'

services:
  rabbitmq:
    image: rabbitmq:3.11.10-management
    container_name: rabbitmq
    restart: always
    ports:
      - 5672:5672
      - 15672:15672
    networks:
      - net-dev


networks:
  net-dev:
    driver: bridge
