version: '3.7'
services:
  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - 6379:6379
    command: redis-server --port 6379
    restart: always
    hostname: redis_boot
    labels:
      - "name=redis"
      - "mode=standalone"
    networks:
      - net-dev

networks:
  net-dev:
    driver: bridge
